# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/carlos/apps/poco-1.6.0
POCO_BUILD = /home/carlos/apps/poco-1.6.0
POCO_PREFIX = /usr/local
POCO_FLAGS = 
OMIT = 
LINKMODE = STATIC
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
export LINKMODE
